### ISSUE TITLE
ECG signal scaling

### ISSUE THREAD

**Issue by baukearends** [antonior92/ecg-age-prediction#5]
I'm having trouble finding details on how the signal is converted to mV by the A/D converter. As mentioned in #1, the statement "All signals are represented as 32-bit floating point numbers at the scale 1e-4 V: so if the signal is in V, it should be multiplied by 1000 before feeding it to the neural network model" suggests that the signal has already been converted to mV. However, when I compare the signal to other databases, the scaling appears inconsistent.

Below is a histogram of the maximum values found in a sample of 100,000 ECGs. I sampled three different datasets, two public datasets (CODE15 and [Shandong](https://pubmed.ncbi.nlm.nih.gov/35672420/)) and one internal dataset (UMCU), each with its own provided scaling/gain information. For all datasets, I applied a Butterworth filter with a low cut of 0.5 Hz to remove baseline wander. Then, I calculated the maximum value for each ECG.

As you can see, the distribution of maximum values for CODE15 (yellow) differs from that of the other two datasets (blue and green). When I empirically scale the CODE15 signals by 0.5, the distributions align more closely. I also tried a scaling factor of 0.39, as suggested in the [instructions](https://www.eletrocardiografodigital.com.br/eletrocardiografo-digital/artigos/teb-referencia-em-aparelho-de-eletrocardiograma-fabricado-no-brasil/) for the original device; however, this scaling provides a slightly less accurate alignment than 0.5.

![Afbeelding van WhatsApp op 2024-11-12 om 11 49 58_11039a26](https://github.com/user-attachments/assets/f0f161ba-e426-4c6b-8301-a50fedbeb462)

**Comment by antonior92** [comment]
Hi, you are absolutely right there was a scaling with factor 2.

I will better document that. Please find details about the preprocessing here: https://github.com/antonior92/ecg-preprocessing (see the last section of the readme there).
